Starting Debug for lxc1-0
Running Command /home/vignesh/Desktop/PLCs/awlsim-0.42/tests/run.sh -e 1 --node 1 /home/vignesh/Desktop/PLCs/awlsim-0.42/tests/modbus/simple_client_server_multiple/sfb102_client.awl
6 (process ID) old priority 0, new priority 10
=== Running tests with 'python2'
Running test 'sfb102_client.awl' with 'python2' ... [u'0', u'10.10.0.9']
[u'1', u'10.10.0.10']
[u'IDS', u'10.10.0.10']
Traceback (most recent call last):
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/tests/../awlsim-cli", line 699, in <module>
    sys.exit(main())
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/tests/../awlsim-cli", line 696, in main
    return run(inputFile,node_id,conn_type)
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/tests/../awlsim-cli", line 274, in run
    s.startup()
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/awlsim/core/main.py", line 163, in startup
    self.cpu.startup()
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/awlsim/core/cpu.py", line 815, in startup
    self.prog.build()
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/awlsim/core/cpu.py", line 435, in build
    sfb = SFB_table[sfbNumber](self.cpu)
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/awlsim/core/systemblocks/system_sfb_102.py", line 213, in __init__
    self.connection_objects[connection_id] = Connection(cpu,connection_id,remote_port,local_port,remote_host_name,is_server,single_write_enabled,data_areas)
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/awlsim/core/systemblocks/connection.py", line 163, in __init__
    self.thread_cmd_arr = Array('i', range(2000))
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/usr/lib/python2.7/multiprocessing/sharedctypes.py", line 119, in Array
    lock = RLock()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 183, in RLock
    return RLock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 172, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 17] File exists
=== TEST FAILED ===
Test 'sfb102_client.awl' FAILED
